export const mockDonors = [
  {
    name: "Ram",
    bloodGroup: "+A",
    district: "Delhi",
    contact: "1234567890",
  },
  {
    name: "Mohan",
    bloodGroup: "+B",
    district: "Mumbai",
    contact: "9876543210",
  },
  {
    name: "Sita",
    bloodGroup: "+A",
    district: "Delhi",
    contact: "5647382910",
  },
  {
    name: "Geeta",
    bloodGroup: "-A",
    district: "Chennai",
    contact: "1010101010",
  },
  {
    name: "Shyam",
    bloodGroup: "-A",
    district: "Dewas",
    contact: "1234567890",
  },
  {
    name: "Radha",
    bloodGroup: "+B",
    district: "Indor",
    contact: "1234567890",
  },
  {
    name: "Krishna",
    bloodGroup: "-B",
    district: "ujjane",
    contact: "1234567890",
  },
  {
    name: "Lakshmi",
    bloodGroup: "+AB",
    district: "Delhi",
    contact: "1234567890",
  },
  {
    name: "Vishnu",
    bloodGroup: "+AB",
    district: "Delhi",
    contact: "1234567890",
  },
  {
    name: "Durga",
    bloodGroup: "O",
    district: "Delhi",
    contact: "1234567890",
  },
  {
    name: "Shiv",
    bloodGroup: "O",
    district: "Shajapur",
    contact: "1234567890",
  },
  {
    name: "Parvati",
    bloodGroup: "-Ab",
    district: "Lakhanv",
    contact: "1234567890",
  },
  {
    name: "Ganesh",
    bloodGroup: "-AB",
    district: "Hedarabad",
    contact: "1234567890",
  },
  {
    name: "Hanuman",
    bloodGroup: "-B",
    district: "Delhi",
    contact: "1234567890",
  },
  {
    name: "Arjun",
    bloodGroup: "+A",
    district: "Jaypur",
    contact: "1234567890",
  },
  {
    name: "Karan",
    bloodGroup: "+B",
    district: "Delhi",
    contact: "1234567890",
  },
  {
    name: "Bhima",
    bloodGroup: "+A",
    district: "Delhi",
    contact: "1234567890",
  },
  {
    name: "Nakula",
    bloodGroup: "+A",
    district: "Delhi",
    contact: "1234567890",
  },
  {
    name: "Sahadeva",
    bloodGroup: "+A",
    district: "Delhi",
    contact: "1234567890",
  },
  {
    name: "Bharat",
    bloodGroup: "-B",
    district: "Shujalpur",
    contact: "1234567890",
  },
  {
    name: "Lakshman",
    bloodGroup: "+AB",
    district: "Baroda",
    contact: "1234567890",
  },
  {
    name: "Bharavi",
    bloodGroup: "O",
    district: "Pune",
    contact: "1234567890",
  },
];
